// ============================================
// RANK TRACKER - Mock Data
// ============================================

import type { RankData } from "../types"
import { AI_OVERVIEW_STATUSES } from "../constants"

/**
 * Mock Ranking Data for Development
 */
export const MOCK_RANK_DATA: RankData[] = [
  {
    id: "1",
    keyword: "best seo software",
    rank: 2,
    previousRank: 6,
    change: 4,
    serpFeatures: ["video", "snippet"],
    volume: 12400,
    url: "/blog/best-seo-tools",
    trendHistory: [15, 12, 10, 8, 6, 5, 4, 3, 2, 2],
    lastUpdated: "2 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[0],
  },
  {
    id: "2",
    keyword: "ai content writer",
    rank: 5,
    previousRank: 7,
    change: 2,
    serpFeatures: ["snippet", "ad"],
    volume: 8900,
    url: "/tools/ai-writer",
    trendHistory: [12, 10, 9, 8, 7, 6, 6, 5, 5, 5],
    lastUpdated: "1 hour ago",
    aiOverview: AI_OVERVIEW_STATUSES[1],
  },
  {
    id: "3",
    keyword: "keyword research tool",
    rank: 8,
    previousRank: 5,
    change: -3,
    serpFeatures: ["video"],
    volume: 14500,
    url: "/features/keyword-magic",
    trendHistory: [4, 5, 5, 6, 6, 7, 7, 8, 8, 8],
    lastUpdated: "3 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[2],
  },
  {
    id: "4",
    keyword: "seo rank tracker",
    rank: 1,
    previousRank: 2,
    change: 1,
    serpFeatures: ["snippet", "video", "ad"],
    volume: 6700,
    url: "/features/rank-tracker",
    trendHistory: [8, 6, 5, 4, 3, 2, 2, 2, 1, 1],
    lastUpdated: "30 mins ago",
    aiOverview: AI_OVERVIEW_STATUSES[0],
  },
  {
    id: "5",
    keyword: "competitor analysis",
    rank: 12,
    previousRank: 12,
    change: 0,
    serpFeatures: ["snippet"],
    volume: 9200,
    url: "/features/competitor-gap",
    trendHistory: [12, 13, 12, 11, 12, 12, 12, 12, 12, 12],
    lastUpdated: "4 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[2],
  },
  {
    id: "6",
    keyword: "content optimization",
    rank: 3,
    previousRank: 8,
    change: 5,
    serpFeatures: ["video", "snippet"],
    volume: 7800,
    url: "/blog/content-optimization",
    trendHistory: [18, 15, 12, 10, 8, 6, 5, 4, 3, 3],
    lastUpdated: "1 hour ago",
    aiOverview: AI_OVERVIEW_STATUSES[1],
  },
  {
    id: "7",
    keyword: "backlink checker",
    rank: 15,
    previousRank: 13,
    change: -2,
    serpFeatures: ["ad"],
    volume: 11300,
    url: "/tools/backlinks",
    trendHistory: [10, 11, 12, 13, 13, 14, 14, 15, 15, 15],
    lastUpdated: "2 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[2],
  },
  {
    id: "8",
    keyword: "serp analysis tool",
    rank: 7,
    previousRank: 10,
    change: 3,
    serpFeatures: ["snippet"],
    volume: 4500,
    url: "/features/serp-analyzer",
    trendHistory: [14, 12, 11, 10, 9, 8, 8, 7, 7, 7],
    lastUpdated: "5 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[0],
  },
  {
    id: "9",
    keyword: "on-page seo checker",
    rank: 4,
    previousRank: 9,
    change: 5,
    serpFeatures: ["snippet", "faq"],
    volume: 5600,
    url: "/tools/on-page-checker",
    trendHistory: [20, 16, 14, 12, 10, 8, 6, 5, 4, 4],
    lastUpdated: "1 hour ago",
    aiOverview: AI_OVERVIEW_STATUSES[1],
  },
  {
    id: "10",
    keyword: "content gap analysis",
    rank: 9,
    previousRank: 6,
    change: -3,
    serpFeatures: ["video"],
    volume: 3200,
    url: "/features/content-gap",
    trendHistory: [4, 5, 5, 6, 6, 7, 8, 8, 9, 9],
    lastUpdated: "6 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[2],
  },
  {
    id: "11",
    keyword: "ai writing assistant",
    rank: 6,
    previousRank: 11,
    change: 5,
    serpFeatures: ["snippet", "ad", "video"],
    volume: 18500,
    url: "/tools/ai-assistant",
    trendHistory: [22, 18, 15, 13, 11, 9, 8, 7, 6, 6],
    lastUpdated: "45 mins ago",
    aiOverview: AI_OVERVIEW_STATUSES[0],
  },
  {
    id: "12",
    keyword: "blog post ideas",
    rank: 18,
    previousRank: 14,
    change: -4,
    serpFeatures: ["faq"],
    volume: 8100,
    url: "/blog/post-ideas",
    trendHistory: [10, 11, 12, 13, 14, 15, 16, 17, 18, 18],
    lastUpdated: "3 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[2],
  },
  {
    id: "13",
    keyword: "seo content strategy",
    rank: 11,
    previousRank: 15,
    change: 4,
    serpFeatures: ["snippet", "video"],
    volume: 6400,
    url: "/blog/seo-strategy",
    trendHistory: [25, 22, 19, 17, 15, 14, 13, 12, 11, 11],
    lastUpdated: "2 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[1],
  },
  {
    id: "14",
    keyword: "keyword density checker",
    rank: 22,
    previousRank: 18,
    change: -4,
    serpFeatures: ["snippet"],
    volume: 2800,
    url: "/tools/keyword-density",
    trendHistory: [14, 15, 16, 17, 18, 19, 20, 21, 22, 22],
    lastUpdated: "8 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[2],
  },
  {
    id: "15",
    keyword: "meta tag generator",
    rank: 2,
    previousRank: 5,
    change: 3,
    serpFeatures: ["snippet", "faq"],
    volume: 4200,
    url: "/tools/meta-generator",
    trendHistory: [12, 10, 8, 7, 6, 5, 4, 3, 2, 2],
    lastUpdated: "1 hour ago",
    aiOverview: AI_OVERVIEW_STATUSES[0],
  },
  {
    id: "16",
    keyword: "domain authority checker",
    rank: 14,
    previousRank: 10,
    change: -4,
    serpFeatures: ["ad"],
    volume: 9800,
    url: "/tools/da-checker",
    trendHistory: [8, 9, 9, 10, 10, 11, 12, 13, 14, 14],
    lastUpdated: "4 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[3],
  },
  {
    id: "17",
    keyword: "featured snippet optimizer",
    rank: 3,
    previousRank: 7,
    change: 4,
    serpFeatures: ["snippet"],
    volume: 1900,
    url: "/tools/snippet-optimizer",
    trendHistory: [15, 13, 11, 9, 8, 7, 5, 4, 3, 3],
    lastUpdated: "2 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[0],
  },
  {
    id: "18",
    keyword: "local seo tools",
    rank: 10,
    previousRank: 10,
    change: 0,
    serpFeatures: ["ad", "shopping"],
    volume: 7300,
    url: "/features/local-seo",
    trendHistory: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
    lastUpdated: "5 hours ago",
    aiOverview: AI_OVERVIEW_STATUSES[1],
  },
]
