// ============================================
// MONETIZATION - Constants & Mock Data
// ============================================

import { BlogNiche, AdNetwork, TrafficMilestone } from "../types"

export const BLOG_NICHES: BlogNiche[] = [
  {
    id: "finance",
    name: "Finance & Investing",
    icon: "??",
    avgRpm: 45,
    minRpm: 25,
    maxRpm: 80,
    description: "High RPM due to valuable financial services ads",
  },
  {
    id: "insurance",
    name: "Insurance",
    icon: "???",
    avgRpm: 55,
    minRpm: 35,
    maxRpm: 100,
    description: "Top-paying niche with premium advertisers",
  },
  {
    id: "legal",
    name: "Legal & Law",
    icon: "??",
    avgRpm: 50,
    minRpm: 30,
    maxRpm: 90,
    description: "High CPC legal ads drive premium RPMs",
  },
  {
    id: "health",
    name: "Health & Wellness",
    icon: "??",
    avgRpm: 25,
    minRpm: 15,
    maxRpm: 45,
    description: "Good RPM with health product advertisers",
  },
  {
    id: "tech",
    name: "Technology",
    icon: "??",
    avgRpm: 20,
    minRpm: 12,
    maxRpm: 35,
    description: "Solid RPM from SaaS and tech product ads",
  },
  {
    id: "travel",
    name: "Travel",
    icon: "??",
    avgRpm: 18,
    minRpm: 10,
    maxRpm: 30,
    description: "Seasonal variations, good affiliate potential",
  },
  {
    id: "food",
    name: "Food & Recipes",
    icon: "??",
    avgRpm: 22,
    minRpm: 15,
    maxRpm: 40,
    description: "Strong with video ads and recipe cards",
  },
  {
    id: "lifestyle",
    name: "Lifestyle",
    icon: "??",
    avgRpm: 15,
    minRpm: 8,
    maxRpm: 25,
    description: "Broad audience, moderate RPM",
  },
  {
    id: "parenting",
    name: "Parenting & Family",
    icon: "????????",
    avgRpm: 20,
    minRpm: 12,
    maxRpm: 35,
    description: "Family product advertisers pay well",
  },
  {
    id: "diy",
    name: "DIY & Crafts",
    icon: "??",
    avgRpm: 18,
    minRpm: 10,
    maxRpm: 30,
    description: "Good engagement, Pinterest traffic bonus",
  },
  {
    id: "gaming",
    name: "Gaming",
    icon: "??",
    avgRpm: 12,
    minRpm: 6,
    maxRpm: 20,
    description: "High traffic but lower RPMs typically",
  },
  {
    id: "education",
    name: "Education & Online Courses",
    icon: "??",
    avgRpm: 25,
    minRpm: 15,
    maxRpm: 45,
    description: "EdTech advertisers pay premium rates",
  },
]

export const AD_NETWORKS: AdNetwork[] = [
  {
    id: "adsense",
    name: "Google AdSense",
    logo: "??",
    minTraffic: 0,
    avgRpm: 8,
    requirements: "No minimum traffic",
    approvalDifficulty: "Easy",
  },
  {
    id: "ezoic",
    name: "Ezoic",
    logo: "??",
    minTraffic: 0,
    avgRpm: 15,
    requirements: "No minimum, AI optimization",
    approvalDifficulty: "Easy",
  },
  {
    id: "monumetric",
    name: "Monumetric",
    logo: "??",
    minTraffic: 10000,
    avgRpm: 20,
    requirements: "10K+ pageviews/month",
    approvalDifficulty: "Medium",
  },
  {
    id: "mediavine",
    name: "Mediavine",
    logo: "??",
    minTraffic: 50000,
    avgRpm: 30,
    requirements: "50K+ sessions/month",
    approvalDifficulty: "Hard",
  },
  {
    id: "raptive",
    name: "Raptive (AdThrive)",
    logo: "??",
    minTraffic: 100000,
    avgRpm: 40,
    requirements: "100K+ pageviews/month",
    approvalDifficulty: "Hard",
  },
]

export const TRAFFIC_MILESTONES: TrafficMilestone[] = [
  {
    pageviews: 1000,
    label: "1K",
    networks: ["AdSense", "Ezoic"],
    avgEarnings: "$8-15/mo",
  },
  {
    pageviews: 10000,
    label: "10K",
    networks: ["Monumetric", "Ezoic"],
    avgEarnings: "$100-200/mo",
  },
  {
    pageviews: 50000,
    label: "50K",
    networks: ["Mediavine"],
    avgEarnings: "$750-1,500/mo",
  },
  {
    pageviews: 100000,
    label: "100K",
    networks: ["Raptive", "Mediavine"],
    avgEarnings: "$2,000-4,000/mo",
  },
  {
    pageviews: 500000,
    label: "500K",
    networks: ["Raptive"],
    avgEarnings: "$15,000-25,000/mo",
  },
  {
    pageviews: 1000000,
    label: "1M",
    networks: ["Raptive"],
    avgEarnings: "$35,000-50,000/mo",
  },
]

export const DEFAULT_CALCULATOR_INPUTS = {
  niche: "tech",
  monthlyPageviews: 50000,
  adNetwork: null,
  customRpm: null,
}
