// Snippet Stealer Mock Data
import type { SnippetOpportunity } from "../types"

export const MOCK_OPPORTUNITIES: SnippetOpportunity[] = [
  {
    id: "1",
    keyword: "how to bake sourdough",
    snippetType: "paragraph",
    volume: 15000,
    status: "ranking",
    currentRank: 4,
    competitorSnippet:
      "To bake sourdough bread, mix flour and water with your starter, let it rise for 4-12 hours, shape the dough, proof overnight in the fridge, then bake at 450°F in a Dutch oven for 45 minutes.",
    competitorWordCount: 42,
    competitorReadingLevel: "Grade 6",
    competitorKeywords: 4,
    targetKeywords: ["sourdough", "starter", "flour", "bake", "dough", "proof", "oven"],
  },
  {
    id: "2",
    keyword: "best time to post on instagram",
    snippetType: "list",
    volume: 22000,
    status: "unclaimed",
    competitorSnippet:
      "The best times to post on Instagram are: Tuesday 11am-2pm, Wednesday 11am, Friday 10-11am. Avoid posting on Sundays. Engagement peaks during lunch hours and mid-week.",
    competitorWordCount: 35,
    competitorReadingLevel: "Grade 5",
    competitorKeywords: 3,
    targetKeywords: ["instagram", "post", "engagement", "time", "tuesday", "wednesday", "friday"],
  },
  {
    id: "3",
    keyword: "how to remove red wine stain",
    snippetType: "list",
    volume: 8500,
    status: "unclaimed",
    competitorSnippet:
      "Blot the stain immediately with a clean cloth. Apply salt or baking soda to absorb the wine. Mix dish soap with hydrogen peroxide and apply. Rinse with cold water and repeat if needed.",
    competitorWordCount: 38,
    competitorReadingLevel: "Grade 5",
    competitorKeywords: 5,
    targetKeywords: ["stain", "wine", "blot", "salt", "baking soda", "rinse", "cloth"],
  },
  {
    id: "4",
    keyword: "what is machine learning",
    snippetType: "paragraph",
    volume: 45000,
    status: "ranking",
    currentRank: 7,
    competitorSnippet:
      "Machine learning is a subset of artificial intelligence that enables computers to learn from data and improve over time without being explicitly programmed. It uses algorithms to identify patterns and make predictions.",
    competitorWordCount: 36,
    competitorReadingLevel: "Grade 8",
    competitorKeywords: 4,
    targetKeywords: ["machine learning", "AI", "artificial intelligence", "algorithms", "data", "patterns", "predictions"],
  },
  {
    id: "5",
    keyword: "how to meditate for beginners",
    snippetType: "list",
    volume: 18000,
    status: "unclaimed",
    competitorSnippet:
      "Find a quiet space, sit comfortably, close your eyes, focus on your breath, and let thoughts pass without judgment. Start with 5 minutes daily and gradually increase the duration.",
    competitorWordCount: 33,
    competitorReadingLevel: "Grade 6",
    competitorKeywords: 3,
    targetKeywords: ["meditate", "breath", "quiet", "focus", "mindfulness", "relax", "beginners"],
  },
  {
    id: "6",
    keyword: "calories in an avocado",
    snippetType: "table",
    volume: 12000,
    status: "ranking",
    currentRank: 3,
    competitorSnippet:
      "A medium avocado (150g) contains approximately 240 calories, 22g of fat, 12g of carbohydrates, and 3g of protein. It's also rich in potassium, fiber, and healthy monounsaturated fats.",
    competitorWordCount: 34,
    competitorReadingLevel: "Grade 7",
    competitorKeywords: 4,
    targetKeywords: ["avocado", "calories", "fat", "protein", "carbohydrates", "potassium", "fiber"],
  },
  {
    id: "7",
    keyword: "how to tie a tie",
    snippetType: "list",
    volume: 33000,
    status: "unclaimed",
    competitorSnippet:
      "Cross the wide end over the narrow end, loop it underneath, bring it across again, pull through the loop around your neck, and tighten. The Four-in-Hand knot is the easiest for beginners.",
    competitorWordCount: 40,
    competitorReadingLevel: "Grade 5",
    competitorKeywords: 4,
    targetKeywords: ["tie", "knot", "loop", "cross", "tighten", "wide end", "narrow end"],
  },
  {
    id: "8",
    keyword: "what is cryptocurrency",
    snippetType: "paragraph",
    volume: 55000,
    status: "ranking",
    currentRank: 5,
    competitorSnippet:
      "Cryptocurrency is a digital or virtual currency that uses cryptography for security and operates on decentralized blockchain technology. Bitcoin, created in 2009, was the first cryptocurrency.",
    competitorWordCount: 30,
    competitorReadingLevel: "Grade 9",
    competitorKeywords: 3,
    targetKeywords: ["cryptocurrency", "bitcoin", "blockchain", "digital", "decentralized", "cryptography", "currency"],
  },
  {
    id: "9",
    keyword: "how to cook rice perfectly",
    snippetType: "paragraph",
    volume: 27000,
    status: "unclaimed",
    competitorSnippet:
      "Rinse rice until water runs clear, use a 1:1.5 rice-to-water ratio, bring to boil, reduce heat and simmer covered for 18 minutes. Let rest 5 minutes before fluffing with a fork.",
    competitorWordCount: 39,
    competitorReadingLevel: "Grade 5",
    competitorKeywords: 5,
    targetKeywords: ["rice", "cook", "boil", "simmer", "water", "rinse", "fluff"],
  },
  {
    id: "10",
    keyword: "benefits of drinking water",
    snippetType: "list",
    volume: 19000,
    status: "ranking",
    currentRank: 6,
    competitorSnippet:
      "Drinking water improves physical performance, boosts brain function, aids digestion, helps with weight loss, flushes toxins, and keeps skin healthy. Aim for 8 glasses daily.",
    competitorWordCount: 29,
    competitorReadingLevel: "Grade 6",
    competitorKeywords: 4,
    targetKeywords: ["water", "hydration", "health", "digestion", "skin", "toxins", "performance"],
  },
  {
    id: "11",
    keyword: "how to save money fast",
    snippetType: "list",
    volume: 31000,
    status: "unclaimed",
    competitorSnippet:
      "Track expenses, create a budget, cut subscriptions, cook at home, automate savings, use cashback apps, and avoid impulse purchases. Setting specific goals helps maintain motivation.",
    competitorWordCount: 28,
    competitorReadingLevel: "Grade 6",
    competitorKeywords: 3,
    targetKeywords: ["save", "money", "budget", "expenses", "savings", "goals", "cashback"],
  },
  {
    id: "12",
    keyword: "what causes hiccups",
    snippetType: "paragraph",
    volume: 9500,
    status: "unclaimed",
    competitorSnippet:
      "Hiccups occur when your diaphragm involuntarily contracts, causing a sudden intake of air that's stopped by the closure of your vocal cords. Common triggers include eating too fast, carbonated drinks, and sudden excitement.",
    competitorWordCount: 41,
    competitorReadingLevel: "Grade 7",
    competitorKeywords: 4,
    targetKeywords: ["hiccups", "diaphragm", "breathing", "spasm", "carbonated", "eating", "triggers"],
  },
]

export const AI_RESPONSES: Record<string, string> = {
  "1": "To bake sourdough, mix active starter with flour and water in a large bowl. Let the dough ferment for 4-6 hours until doubled in size. Shape into a round loaf, proof overnight in the fridge, then bake at 450°F in a preheated Dutch oven for 40-45 minutes until golden brown with a crispy crust.",
  "2": "The best times to post on Instagram for maximum engagement are Tuesday and Wednesday between 10am-1pm, Thursday at 11am, and Friday from 10-11am. Avoid posting late nights and Sundays when engagement drops significantly. Use Instagram Insights to find your specific audience's peak activity times.",
  "3": "To remove a red wine stain, act immediately by blotting with a clean white cloth. Cover the stain with salt or baking soda to absorb excess wine. Mix one tablespoon dish soap with one tablespoon hydrogen peroxide, apply to the stain, let sit for 30 minutes, then rinse with cold water.",
  "4": "Machine learning is a branch of artificial intelligence where computers learn patterns from data without explicit programming. It uses algorithms to analyze datasets, identify patterns, and make predictions or decisions. Applications include recommendation systems, image recognition, natural language processing, and autonomous vehicles.",
  "5": "To meditate as a beginner, find a quiet space and sit comfortably with your back straight. Close your eyes, breathe naturally, and focus attention on your breath. When thoughts arise, acknowledge them without judgment and return focus to breathing. Start with 5-10 minutes daily, gradually increasing duration.",
  "6": "A medium avocado (150g) contains approximately 240 calories, 22g of healthy fats, 12g of carbohydrates, 10g of fiber, and 3g of protein. Avocados are also rich in potassium (more than bananas), vitamin K, vitamin E, vitamin C, and heart-healthy monounsaturated fats.",
  "7": "To tie a tie using the Four-in-Hand knot: Start with the wide end on your right, crossing over the narrow end. Loop the wide end underneath and back across. Pull the wide end up through the neck loop from behind, then down through the front knot. Tighten by holding the narrow end and sliding the knot up.",
  "8": "Cryptocurrency is a decentralized digital currency secured by cryptography and recorded on blockchain technology. Unlike traditional currencies, it operates without central banks or governments. Bitcoin, launched in 2009, was the first cryptocurrency. Today, thousands exist including Ethereum, Litecoin, and stablecoins pegged to fiat currencies.",
  "9": "To cook perfect rice, rinse thoroughly until water runs clear to remove excess starch. Use a 1:1.5 ratio of rice to water. Bring to a boil, then reduce heat to low and cover tightly. Simmer for 18 minutes without lifting the lid. Remove from heat and let rest 5 minutes before fluffing with a fork.",
  "10": "Drinking adequate water provides numerous health benefits: improves physical performance and energy levels, boosts brain function and concentration, aids digestion and prevents constipation, supports kidney function and flushes toxins, promotes healthy skin, and can assist with weight management by reducing hunger. Aim for 8 glasses (2 liters) daily.",
  "11": "To save money fast: Track all expenses for one month to identify spending patterns. Create a realistic budget allocating income to needs, wants, and savings. Cancel unused subscriptions. Cook meals at home instead of dining out. Automate transfers to savings accounts. Use cashback apps and coupons. Avoid impulse purchases by implementing a 24-hour waiting rule.",
  "12": "Hiccups occur when the diaphragm muscle involuntarily contracts, causing a sudden intake of breath that's abruptly stopped by the closure of the vocal cords, producing the characteristic 'hic' sound. Common triggers include eating too quickly, consuming carbonated beverages, sudden temperature changes, excitement, and swallowing air.",
}

export const DEFAULT_AI_RESPONSE_TEMPLATE = (keyword: string) =>
  `${keyword.charAt(0).toUpperCase() + keyword.slice(1)} is simple when you follow these proven steps. First, prepare your materials and workspace properly. Next, follow the technique carefully for optimal results. The key is consistency and patience. Most people see success within their first few attempts when following this method correctly.`
