import { WeakSpotKeyword } from "../types/weak-spot.types"

// ============================================
// MOCK DATA - Reddit/Quora/Forum Rankings
// ============================================
export const WEAK_SPOT_DATA: WeakSpotKeyword[] = [
  {
    id: "ws1",
    keyword: "best ai writing tools 2024",
    volume: 12500,
    kd: 18,
    intent: "commercial",
    weakSpotType: "reddit",
    weakSpotRank: 2,
    weakSpotUrl: "https://reddit.com/r/artificial/comments/abc123",
    weakSpotTitle: "What AI writing tools are you guys using? Thread getting outdated",
    yourRank: null,
    opportunity: "high",
    trafficPotential: 8500
  },
  {
    id: "ws2",
    keyword: "chatgpt vs claude for coding",
    volume: 8900,
    kd: 22,
    intent: "informational",
    weakSpotType: "reddit",
    weakSpotRank: 1,
    weakSpotUrl: "https://reddit.com/r/programming/comments/def456",
    weakSpotTitle: "ChatGPT or Claude for coding? Need opinions (6 months old)",
    yourRank: 15,
    opportunity: "high",
    trafficPotential: 6200
  },
  {
    id: "ws3",
    keyword: "how to do keyword research",
    volume: 22000,
    kd: 35,
    intent: "informational",
    weakSpotType: "quora",
    weakSpotRank: 4,
    weakSpotUrl: "https://quora.com/How-do-I-do-keyword-research",
    weakSpotTitle: "How do I do keyword research for my blog? - Generic 2019 answer",
    yourRank: 28,
    opportunity: "medium",
    trafficPotential: 4800
  },
  {
    id: "ws4",
    keyword: "seo tools comparison 2024",
    volume: 6700,
    kd: 28,
    intent: "commercial",
    weakSpotType: "linkedin",
    weakSpotRank: 3,
    weakSpotUrl: "https://linkedin.com/pulse/best-seo-tools-2023",
    weakSpotTitle: "Best SEO Tools 2023 - LinkedIn Pulse Article (Outdated)",
    yourRank: null,
    opportunity: "high",
    trafficPotential: 4200
  },
  {
    id: "ws5",
    keyword: "content marketing strategy examples",
    volume: 14200,
    kd: 32,
    intent: "informational",
    weakSpotType: "medium",
    weakSpotRank: 5,
    weakSpotUrl: "https://medium.com/@marketer/content-strategy",
    weakSpotTitle: "My Content Marketing Strategy - Personal Blog Post",
    yourRank: 12,
    opportunity: "medium",
    trafficPotential: 3500
  },
  {
    id: "ws6",
    keyword: "free seo audit tools",
    volume: 9800,
    kd: 24,
    intent: "transactional",
    weakSpotType: "reddit",
    weakSpotRank: 3,
    weakSpotUrl: "https://reddit.com/r/SEO/comments/ghi789",
    weakSpotTitle: "Best free SEO audit tools? Thread from 2 years ago",
    yourRank: null,
    opportunity: "high",
    trafficPotential: 5800
  },
  {
    id: "ws7",
    keyword: "ai content writing tips",
    volume: 5400,
    kd: 19,
    intent: "informational",
    weakSpotType: "quora",
    weakSpotRank: 2,
    weakSpotUrl: "https://quora.com/What-are-tips-for-AI-content",
    weakSpotTitle: "Tips for using AI to write content - Basic answer",
    yourRank: 22,
    opportunity: "high",
    trafficPotential: 3800
  },
  {
    id: "ws8",
    keyword: "how to rank on google fast",
    volume: 18500,
    kd: 42,
    intent: "informational",
    weakSpotType: "reddit",
    weakSpotRank: 6,
    weakSpotUrl: "https://reddit.com/r/SEO/comments/jkl012",
    weakSpotTitle: "How to rank faster? Outdated advice thread",
    yourRank: 35,
    opportunity: "medium",
    trafficPotential: 2800
  },
  {
    id: "ws9",
    keyword: "jasper ai alternatives",
    volume: 7200,
    kd: 26,
    intent: "commercial",
    weakSpotType: "reddit",
    weakSpotRank: 1,
    weakSpotUrl: "https://reddit.com/r/EntrepreneurRideAlong/mno345",
    weakSpotTitle: "Looking for Jasper alternatives - Thread from last year",
    yourRank: null,
    opportunity: "high",
    trafficPotential: 5100
  },
  {
    id: "ws10",
    keyword: "blog post optimization checklist",
    volume: 4100,
    kd: 21,
    intent: "informational",
    weakSpotType: "medium",
    weakSpotRank: 4,
    weakSpotUrl: "https://medium.com/seo-tips/optimization-checklist",
    weakSpotTitle: "SEO Checklist - Basic Medium article",
    yourRank: 18,
    opportunity: "high",
    trafficPotential: 2900
  },
  {
    id: "ws11",
    keyword: "best blogging platform 2024",
    volume: 15600,
    kd: 31,
    intent: "commercial",
    weakSpotType: "reddit",
    weakSpotRank: 2,
    weakSpotUrl: "https://reddit.com/r/Blogging/comments/pqr678",
    weakSpotTitle: "What platform should I use for blogging? (Old recommendations)",
    yourRank: null,
    opportunity: "high",
    trafficPotential: 9200
  },
  {
    id: "ws12",
    keyword: "email marketing tools comparison",
    volume: 11200,
    kd: 38,
    intent: "commercial",
    weakSpotType: "quora",
    weakSpotRank: 5,
    weakSpotUrl: "https://quora.com/best-email-marketing-tools",
    weakSpotTitle: "What are the best email marketing tools? - 2021 answers",
    yourRank: 42,
    opportunity: "medium",
    trafficPotential: 3100
  }
]
