// ============================================
// CONTENT DECAY - Mock Data
// ============================================

import type { DecayArticle, RecoveredArticle, DecayAlert } from "../types"

export const MOCK_DECAY_DATA: DecayArticle[] = [
  {
    id: "1",
    title: "Best Gaming Laptops 2024",
    url: "https://myblog.com/best-gaming-laptops-2024",
    currentRank: 8,
    previousRank: 3,
    trafficLoss: -1200,
    decayReason: "Competitor",
    trendData: [85, 78, 72, 65, 58, 52, 48, 42],
    status: "critical",
    decayRate: 0.85,
    trafficValue: 0.9,
    lastUpdated: "2024-01-15",
  },
  {
    id: "2",
    title: "Top 10 JavaScript Frameworks",
    url: "https://myblog.com/javascript-frameworks",
    currentRank: 12,
    previousRank: 5,
    trafficLoss: -2100,
    decayReason: "Missing Keywords",
    trendData: [92, 88, 80, 72, 65, 55, 48, 40],
    status: "critical",
    decayRate: 0.92,
    trafficValue: 0.95,
    lastUpdated: "2024-01-10",
  },
  {
    id: "3",
    title: "Complete SEO Guide for Beginners",
    url: "https://myblog.com/seo-guide-beginners",
    currentRank: 15,
    previousRank: 4,
    trafficLoss: -1800,
    decayReason: "Outdated",
    trendData: [88, 82, 75, 68, 60, 52, 45, 38],
    status: "critical",
    decayRate: 0.78,
    trafficValue: 0.88,
    lastUpdated: "2023-06-20",
  },
  {
    id: "4",
    title: "How to Start a Blog in 2024",
    url: "https://myblog.com/start-blog-2024",
    currentRank: 6,
    previousRank: 4,
    trafficLoss: -450,
    decayReason: "Competitor",
    trendData: [75, 73, 70, 68, 65, 62, 60, 58],
    status: "watch",
    decayRate: 0.35,
    trafficValue: 0.7,
    lastUpdated: "2024-02-01",
  },
  {
    id: "5",
    title: "Email Marketing Best Practices",
    url: "https://myblog.com/email-marketing-best-practices",
    currentRank: 9,
    previousRank: 7,
    trafficLoss: -320,
    decayReason: "Schema Issues",
    trendData: [68, 66, 64, 62, 60, 58, 56, 55],
    status: "watch",
    decayRate: 0.25,
    trafficValue: 0.5,
    lastUpdated: "2024-01-28",
  },
  {
    id: "6",
    title: "Python vs JavaScript: Which to Learn?",
    url: "https://myblog.com/python-vs-javascript",
    currentRank: 11,
    previousRank: 6,
    trafficLoss: -890,
    decayReason: "Missing Keywords",
    trendData: [80, 75, 70, 65, 60, 55, 50, 48],
    status: "watch",
    decayRate: 0.45,
    trafficValue: 0.65,
    lastUpdated: "2024-01-20",
  },
  {
    id: "7",
    title: "Best WordPress Themes 2024",
    url: "https://myblog.com/best-wordpress-themes",
    currentRank: 14,
    previousRank: 8,
    trafficLoss: -1100,
    decayReason: "Outdated",
    trendData: [72, 68, 62, 58, 52, 48, 45, 42],
    status: "critical",
    decayRate: 0.72,
    trafficValue: 0.75,
    lastUpdated: "2023-09-15",
  },
  {
    id: "8",
    title: "React Hooks Tutorial",
    url: "https://myblog.com/react-hooks-tutorial",
    currentRank: 7,
    previousRank: 5,
    trafficLoss: -280,
    decayReason: "Slow Load",
    trendData: [82, 80, 78, 76, 74, 72, 70, 68],
    status: "watch",
    decayRate: 0.2,
    trafficValue: 0.8,
    lastUpdated: "2024-02-05",
  },
]

export const RECOVERED_ARTICLES: RecoveredArticle[] = [
  {
    id: "r1",
    title: "SEO Guide for E-commerce",
    trafficGain: "+20%",
    daysAgo: 3,
  },
  {
    id: "r2",
    title: "Social Media Strategy 2024",
    trafficGain: "+35%",
    daysAgo: 7,
  },
  {
    id: "r3",
    title: "Content Marketing Tips",
    trafficGain: "+18%",
    daysAgo: 12,
  },
]

export const MOCK_ALERTS: DecayAlert[] = [
  {
    id: "alert1",
    title: "🚨 Critical Decay Detected",
    message: "\"Best Gaming Laptops 2024\" dropped 5 positions in 24h - immediate action required",
    severity: "critical",
    timestamp: "2 hours ago",
    articleId: "1",
    actionTaken: false,
    channel: "push",
  },
  {
    id: "alert2",
    title: "⚠️ Competitor Update Alert",
    message: "Competitor ahrefs.com updated their SEO guide - your content may need refresh",
    severity: "warning",
    timestamp: "5 hours ago",
    articleId: "3",
    actionTaken: false,
    channel: "email",
  },
  {
    id: "alert3",
    title: "📉 Traffic Decline Pattern",
    message: "3 articles showing consistent traffic decline over past week",
    severity: "warning",
    timestamp: "8 hours ago",
    articleId: null,
    actionTaken: true,
    channel: "slack",
  },
  {
    id: "alert4",
    title: "🔍 Schema Issues Found",
    message: "\"Email Marketing Best Practices\" missing FAQ schema - easy win opportunity",
    severity: "info",
    timestamp: "1 day ago",
    articleId: "5",
    actionTaken: false,
    channel: "email",
  },
  {
    id: "alert5",
    title: "⏰ Scheduled Refresh Due",
    message: "\"Python vs JavaScript\" is due for quarterly refresh based on your calendar",
    severity: "info",
    timestamp: "1 day ago",
    articleId: "6",
    actionTaken: true,
    channel: "push",
  },
]
