// On-Page Checker Mock Data
import type { PageStructureItem, IssuesData, NLPKeyword } from "../types"

export const MOCK_PAGE_STRUCTURE: PageStructureItem[] = [
  { tag: "H1", content: "Complete Guide to SEO in 2024", status: "good" },
  { tag: "IMG", content: "hero-image.jpg - Alt tag missing", status: "error" },
  { tag: "P", content: "Introduction paragraph with keyword...", status: "good" },
  { tag: "H2", content: "What is SEO?", status: "good" },
  { tag: "P", content: "SEO stands for Search Engine...", status: "good" },
  { tag: "IMG", content: "diagram.png - Good alt text", status: "good" },
  { tag: "H2", content: "On-Page SEO Factors", status: "good" },
  { tag: "H3", content: "Title Tags", status: "warning" },
  { tag: "P", content: "Title tags are important for...", status: "good" },
  { tag: "A", content: "External link - No rel attribute", status: "warning" },
  { tag: "H2", content: "Technical SEO", status: "good" },
  { tag: "P", content: "Technical SEO involves...", status: "good" },
]

export const MOCK_ISSUES: IssuesData = {
  errors: [
    {
      id: 1,
      title: "Meta Description Missing",
      description: "Your page doesn't have a meta description. This affects CTR in search results.",
      element: "<meta name='description'>",
      impact: "High",
      canAiFix: true,
      aiSuggestion: "Discover the complete guide to SEO in 2024. Learn proven strategies for on-page optimization, technical SEO, and content marketing to boost your search rankings and drive organic traffic.",
    },
    {
      id: 2,
      title: "Alt Tag Missing on 1 Image",
      description: "hero-image.jpg is missing alt text for accessibility and SEO.",
      element: "<img src='hero-image.jpg'>",
      impact: "Medium",
      canAiFix: true,
      aiSuggestion: "SEO guide infographic showing the key elements of search engine optimization including keywords, backlinks, and content strategy",
    },
    {
      id: 3,
      title: "H1 Tag Too Long",
      description: "Your H1 is 68 characters. Recommended: under 60 characters.",
      element: "<h1>",
      impact: "Medium",
      canAiFix: true,
      aiSuggestion: "Complete SEO Guide 2024: Boost Rankings",
    },
  ],
  warnings: [
    {
      id: 4,
      title: "Keyword Density Low (0.4%)",
      description: "Target keyword appears only 3 times. Competitors average 8-12 mentions.",
      element: "Content Body",
      impact: "Medium",
      canAiFix: false,
    },
    {
      id: 5,
      title: "External Links Missing rel Attribute",
      description: "2 external links should have rel='noopener' for security.",
      element: "<a href='...'>",
      impact: "Low",
      canAiFix: false,
    },
    {
      id: 6,
      title: "Subheading H3 Could Be Improved",
      description: "'Title Tags' is too generic. Consider more descriptive headings.",
      element: "<h3>",
      impact: "Low",
      canAiFix: true,
      aiSuggestion: "How to Optimize Title Tags for Maximum Click-Through Rate",
    },
    {
      id: 13,
      title: "No Schema Markup Found",
      description: "Your page has no structured data. Adding Schema.org markup improves rich snippet visibility in search results.",
      element: "<script type='application/ld+json'>",
      impact: "Medium",
      canAiFix: false,
      schemaType: "missing",
    },
  ],
  passed: [
    { id: 7, title: "Title Tag Present", description: "Good title tag with target keyword." },
    { id: 8, title: "URL Structure Optimized", description: "Clean, keyword-rich URL slug." },
    { id: 9, title: "Internal Links Found", description: "5 internal links detected." },
    { id: 10, title: "Mobile Responsive", description: "Page passes mobile-friendliness test." },
    { id: 11, title: "SSL Certificate Valid", description: "HTTPS is properly configured." },
    { id: 12, title: "Canonical Tag Present", description: "Correct canonical URL specified." },
  ],
}

export const MOCK_NLP_KEYWORDS: NLPKeyword[] = [
  { keyword: "SEO", density: "2.4%", volume: 110000, status: "optimal", suggestion: "Perfect density. Keep this level." },
  { keyword: "search engine optimization", density: "1.2%", volume: 74000, status: "optimal", suggestion: "Good usage of long-tail variant." },
  { keyword: "on-page SEO", density: "0.8%", volume: 33100, status: "underused", suggestion: "Consider adding 2-3 more mentions." },
  { keyword: "keywords", density: "1.8%", volume: 165000, status: "optimal", suggestion: "Well distributed throughout content." },
  { keyword: "meta tags", density: "0.3%", volume: 27100, status: "underused", suggestion: "Add to H2 or intro paragraph." },
  { keyword: "ranking factors", density: "0.4%", volume: 22200, status: "underused", suggestion: "Add to conclusion section." },
  { keyword: "Google algorithm", density: "0.2%", volume: 49500, status: "underused", suggestion: "Add to technical SEO section." },
  { keyword: "backlinks", density: "1.6%", volume: 60500, status: "optimal", suggestion: "Good coverage in content." },
  { keyword: "content optimization", density: "0.5%", volume: 14800, status: "underused", suggestion: "Add to H2 heading." },
  { keyword: "SERP", density: "0.9%", volume: 40500, status: "optimal", suggestion: "Well-placed mentions." },
  { keyword: "title tag", density: "1.4%", volume: 18100, status: "optimal", suggestion: "Appropriate usage level." },
  { keyword: "anchor text", density: "0.2%", volume: 12100, status: "underused", suggestion: "Add to links section." },
  { keyword: "internal linking", density: "0.7%", volume: 9900, status: "optimal", suggestion: "Good contextual placement." },
  { keyword: "page speed", density: "0.3%", volume: 27100, status: "underused", suggestion: "Add to technical SEO section." },
  { keyword: "mobile-first", density: "0.1%", volume: 8100, status: "underused", suggestion: "Add to mobile optimization section." },
  { keyword: "schema markup", density: "0.2%", volume: 14800, status: "underused", suggestion: "Add to structured data section." },
  { keyword: "user experience", density: "0.6%", volume: 60500, status: "optimal", suggestion: "Good semantic relevance." },
  { keyword: "bounce rate", density: "0.3%", volume: 90500, status: "underused", suggestion: "Add to metrics section." },
  { keyword: "crawlability", density: "0.1%", volume: 2900, status: "underused", suggestion: "Add to technical SEO section." },
  { keyword: "indexing", density: "3.2%", volume: 40500, status: "overused", suggestion: "Reduce by 1-2 mentions to avoid keyword stuffing." },
]
