// ============================================
// CONTENT ROADMAP - Mock Data
// ============================================

import type { TaskCard } from "../types"

const now = new Date().toISOString()

export const INITIAL_TASKS: TaskCard[] = [
  {
    id: "1",
    title: "How to use AI for SEO",
    keyword: "ai seo tools",
    volume: 12000,
    volumeDisplay: "12k",
    kd: 45,
    priorityScore: 98,
    assignee: "JD",
    status: "backlog",
    dueDate: "2025-12-20",
    tags: ["guide", "tutorial"],
    comments: [],
    progress: 0,
    targetWordCount: 2500,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "2",
    title: "Best keyword research strategies",
    keyword: "keyword research",
    volume: 8500,
    volumeDisplay: "8.5k",
    kd: 52,
    priorityScore: 92,
    assignee: "AM",
    status: "backlog",
    dueDate: "2025-12-22",
    tags: ["guide"],
    comments: [],
    progress: 0,
    targetWordCount: 3000,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "3",
    title: "Technical SEO checklist 2025",
    keyword: "technical seo",
    volume: 6200,
    volumeDisplay: "6.2k",
    kd: 38,
    priorityScore: 88,
    assignee: "JD",
    status: "backlog",
    dueDate: "2025-12-25",
    tags: ["listicle"],
    comments: [],
    progress: 0,
    targetWordCount: 2000,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "4",
    title: "Link building guide for beginners",
    keyword: "link building",
    volume: 5800,
    volumeDisplay: "5.8k",
    kd: 61,
    priorityScore: 75,
    assignee: "SK",
    status: "backlog",
    tags: ["guide", "tutorial"],
    comments: [],
    progress: 0,
    targetWordCount: 3500,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "5",
    title: "Content optimization tips",
    keyword: "seo content",
    volume: 4100,
    volumeDisplay: "4.1k",
    kd: 33,
    priorityScore: 82,
    assignee: "AM",
    status: "ready",
    dueDate: "2025-12-18",
    tags: ["blog", "listicle"],
    comments: [{ id: "c1", text: "Add more examples", author: "JD", createdAt: now }],
    progress: 0,
    targetWordCount: 1800,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "6",
    title: "Local SEO strategies",
    keyword: "local seo",
    volume: 9300,
    volumeDisplay: "9.3k",
    kd: 47,
    priorityScore: 85,
    assignee: "JD",
    status: "ready",
    dueDate: "2025-12-19",
    tags: ["guide"],
    comments: [],
    progress: 0,
    targetWordCount: 2800,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "7",
    title: "SEO for e-commerce sites",
    keyword: "ecommerce seo",
    volume: 7200,
    volumeDisplay: "7.2k",
    kd: 55,
    priorityScore: 79,
    assignee: "SK",
    status: "ready",
    tags: ["guide", "case-study"],
    comments: [],
    progress: 0,
    targetWordCount: 4000,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "8",
    title: "Voice search optimization",
    keyword: "voice search seo",
    volume: 3400,
    volumeDisplay: "3.4k",
    kd: 29,
    priorityScore: 71,
    assignee: "AM",
    status: "progress",
    dueDate: "2025-12-16",
    tags: ["blog", "news"],
    comments: [{ id: "c2", text: "Almost done with draft", author: "AM", createdAt: now }],
    progress: 65,
    wordCount: 1400,
    targetWordCount: 2000,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "9",
    title: "Mobile SEO best practices",
    keyword: "mobile seo",
    volume: 5100,
    volumeDisplay: "5.1k",
    kd: 41,
    priorityScore: 77,
    assignee: "JD",
    status: "progress",
    dueDate: "2025-12-17",
    tags: ["listicle", "tutorial"],
    comments: [],
    progress: 40,
    wordCount: 1000,
    targetWordCount: 2500,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "10",
    title: "Complete SEO audit guide",
    keyword: "seo audit",
    volume: 11000,
    volumeDisplay: "11k",
    kd: 58,
    priorityScore: 94,
    assignee: "SK",
    status: "published",
    dueDate: "2025-12-10",
    tags: ["guide", "tutorial"],
    comments: [],
    progress: 100,
    wordCount: 3200,
    targetWordCount: 3000,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "11",
    title: "On-page SEO fundamentals",
    keyword: "on-page seo",
    volume: 15000,
    volumeDisplay: "15k",
    kd: 62,
    priorityScore: 91,
    assignee: "JD",
    status: "published",
    dueDate: "2025-12-08",
    tags: ["guide"],
    comments: [],
    progress: 100,
    wordCount: 2800,
    targetWordCount: 2500,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "12",
    title: "Backlink analysis tutorial",
    keyword: "backlink analysis",
    volume: 4800,
    volumeDisplay: "4.8k",
    kd: 44,
    priorityScore: 73,
    assignee: "AM",
    status: "published",
    dueDate: "2025-12-05",
    tags: ["tutorial", "review"],
    comments: [],
    progress: 100,
    wordCount: 2200,
    targetWordCount: 2000,
    createdAt: now,
    updatedAt: now,
  },
]
