// Affiliate Keyword Finder Constants

import { AffiliateProgram, AffiliateNiche, IntentModifier, BuyerIntent } from "../types"

// Intent modifier patterns with scores
export const INTENT_MODIFIERS: Record<IntentModifier, { 
  label: string
  score: number 
  description: string
  icon: string
}> = {
  best: { label: "Best", score: 90, description: "Roundup/listicle intent", icon: "🏆" },
  review: { label: "Review", score: 95, description: "Single product review", icon: "⭐" },
  vs: { label: "vs/Versus", score: 85, description: "Comparison shopping", icon: "⚔️" },
  alternative: { label: "Alternative", score: 88, description: "Looking for options", icon: "🔄" },
  comparison: { label: "Comparison", score: 85, description: "Comparing products", icon: "⚖️" },
  top: { label: "Top", score: 80, description: "Best picks list", icon: "📊" },
  cheapest: { label: "Cheapest", score: 75, description: "Budget conscious", icon: "💰" },
  discount: { label: "Discount", score: 92, description: "Ready to buy", icon: "🏷️" },
  coupon: { label: "Coupon", score: 95, description: "Immediate purchase", icon: "🎟️" },
  deal: { label: "Deal", score: 90, description: "Looking for offers", icon: "🔥" },
  buy: { label: "Buy", score: 98, description: "Transactional intent", icon: "🛒" },
  price: { label: "Price", score: 70, description: "Price research", icon: "💵" },
  "worth it": { label: "Worth It", score: 82, description: "Purchase validation", icon: "🤔" },
  "pros cons": { label: "Pros/Cons", score: 80, description: "Decision making", icon: "📝" },
}

// Buyer intent descriptions
export const BUYER_INTENT_CONFIG: Record<BuyerIntent, {
  label: string
  color: string
  bgColor: string
  description: string
  conversionRate: string
}> = {
  transactional: {
    label: "Transactional",
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
    description: "Ready to buy",
    conversionRate: "8-15%",
  },
  commercial: {
    label: "Commercial",
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
    description: "Researching to buy",
    conversionRate: "3-8%",
  },
  informational: {
    label: "Informational",
    color: "text-amber-400",
    bgColor: "bg-amber-500/10",
    description: "Learning/researching",
    conversionRate: "0.5-2%",
  },
  navigational: {
    label: "Navigational",
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    description: "Looking for specific site",
    conversionRate: "1-3%",
  },
}

// Popular affiliate programs
export const AFFILIATE_PROGRAMS: AffiliateProgram[] = [
  {
    id: "amazon",
    name: "Amazon Associates",
    logo: "🛒",
    category: "General",
    commissionRate: "1-10%",
    commissionType: "percentage",
    cookieDuration: 24, // hours converted to days = 1
    avgOrderValue: 50,
    payoutThreshold: 10,
    rating: 4.2,
    popularity: "high",
  },
  {
    id: "shareasale",
    name: "ShareASale",
    logo: "🔗",
    category: "Network",
    commissionRate: "5-50%",
    commissionType: "percentage",
    cookieDuration: 30,
    avgOrderValue: 80,
    payoutThreshold: 50,
    rating: 4.5,
    popularity: "high",
  },
  {
    id: "cj",
    name: "CJ Affiliate",
    logo: "🌐",
    category: "Network",
    commissionRate: "3-30%",
    commissionType: "percentage",
    cookieDuration: 45,
    avgOrderValue: 100,
    payoutThreshold: 50,
    rating: 4.3,
    popularity: "high",
  },
  {
    id: "impact",
    name: "Impact",
    logo: "💥",
    category: "Network",
    commissionRate: "5-40%",
    commissionType: "percentage",
    cookieDuration: 30,
    avgOrderValue: 120,
    payoutThreshold: 25,
    rating: 4.6,
    popularity: "medium",
  },
  {
    id: "bluehost",
    name: "Bluehost",
    logo: "🔵",
    category: "Hosting",
    commissionRate: "$65-130",
    commissionType: "flat",
    cookieDuration: 90,
    avgOrderValue: 100,
    payoutThreshold: 100,
    rating: 4.4,
    popularity: "high",
  },
  {
    id: "semrush",
    name: "SEMrush",
    logo: "📊",
    category: "SEO Tools",
    commissionRate: "$200 + 40%",
    commissionType: "recurring",
    cookieDuration: 120,
    avgOrderValue: 120,
    payoutThreshold: 50,
    rating: 4.7,
    popularity: "medium",
  },
  {
    id: "convertkit",
    name: "ConvertKit",
    logo: "✉️",
    category: "Email Marketing",
    commissionRate: "30%",
    commissionType: "recurring",
    cookieDuration: 60,
    avgOrderValue: 50,
    payoutThreshold: 80,
    rating: 4.5,
    popularity: "medium",
  },
  {
    id: "canva",
    name: "Canva",
    logo: "🎨",
    category: "Design",
    commissionRate: "$36",
    commissionType: "flat",
    cookieDuration: 30,
    avgOrderValue: 120,
    payoutThreshold: 10,
    rating: 4.3,
    popularity: "high",
  },
]

// Affiliate niches
export const AFFILIATE_NICHES: AffiliateNiche[] = [
  {
    id: "hosting",
    name: "Web Hosting",
    icon: "🌐",
    avgCommission: "$50-150",
    topPrograms: ["Bluehost", "SiteGround", "Hostinger"],
    competitionLevel: "high",
    growthTrend: "stable",
  },
  {
    id: "seo-tools",
    name: "SEO Tools",
    icon: "📊",
    avgCommission: "$50-200",
    topPrograms: ["SEMrush", "Ahrefs", "Mangools"],
    competitionLevel: "high",
    growthTrend: "growing",
  },
  {
    id: "email-marketing",
    name: "Email Marketing",
    icon: "✉️",
    avgCommission: "20-40%",
    topPrograms: ["ConvertKit", "AWeber", "GetResponse"],
    competitionLevel: "medium",
    growthTrend: "growing",
  },
  {
    id: "vpn",
    name: "VPN Services",
    icon: "🔒",
    avgCommission: "30-100%",
    topPrograms: ["NordVPN", "ExpressVPN", "Surfshark"],
    competitionLevel: "high",
    growthTrend: "stable",
  },
  {
    id: "finance",
    name: "Finance/Banking",
    icon: "💰",
    avgCommission: "$50-200",
    topPrograms: ["Credit Cards", "Investing Apps", "Insurance"],
    competitionLevel: "high",
    growthTrend: "growing",
  },
  {
    id: "online-courses",
    name: "Online Courses",
    icon: "🎓",
    avgCommission: "20-50%",
    topPrograms: ["Udemy", "Skillshare", "Coursera"],
    competitionLevel: "medium",
    growthTrend: "growing",
  },
  {
    id: "software",
    name: "Software/SaaS",
    icon: "💻",
    avgCommission: "15-40%",
    topPrograms: ["Adobe", "Microsoft", "Notion"],
    competitionLevel: "medium",
    growthTrend: "growing",
  },
  {
    id: "fitness",
    name: "Fitness/Health",
    icon: "💪",
    avgCommission: "5-20%",
    topPrograms: ["Supplements", "Equipment", "Programs"],
    competitionLevel: "high",
    growthTrend: "stable",
  },
]

// Sample affiliate keywords for demo (50+ keywords)
export const SAMPLE_AFFILIATE_KEYWORDS = [
  // Web Hosting
  {
    keyword: "best web hosting for bloggers",
    volume: 8100,
    kd: 45,
    cpc: 12.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "hosting",
    affiliateScore: 92,
  },
  {
    keyword: "bluehost discount",
    volume: 6600,
    kd: 42,
    cpc: 15.30,
    intent: "transactional" as BuyerIntent,
    modifiers: ["discount"] as IntentModifier[],
    niche: "hosting",
    affiliateScore: 96,
  },
  {
    keyword: "siteground vs bluehost",
    volume: 12400,
    kd: 48,
    cpc: 14.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "hosting",
    affiliateScore: 91,
  },
  {
    keyword: "hostinger review 2024",
    volume: 9800,
    kd: 38,
    cpc: 10.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "hosting",
    affiliateScore: 89,
  },
  {
    keyword: "best wordpress hosting",
    volume: 22000,
    kd: 58,
    cpc: 16.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "hosting",
    affiliateScore: 94,
  },
  {
    keyword: "cheapest web hosting",
    volume: 18500,
    kd: 52,
    cpc: 11.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["cheapest"] as IntentModifier[],
    niche: "hosting",
    affiliateScore: 85,
  },
  {
    keyword: "cloudways coupon code",
    volume: 3200,
    kd: 28,
    cpc: 18.90,
    intent: "transactional" as BuyerIntent,
    modifiers: ["coupon"] as IntentModifier[],
    niche: "hosting",
    affiliateScore: 97,
  },

  // SEO Tools
  {
    keyword: "semrush vs ahrefs",
    volume: 14800,
    kd: 52,
    cpc: 18.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "seo-tools",
    affiliateScore: 95,
  },
  {
    keyword: "best seo tools 2024",
    volume: 27000,
    kd: 62,
    cpc: 22.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "seo-tools",
    affiliateScore: 93,
  },
  {
    keyword: "ahrefs review",
    volume: 8900,
    kd: 45,
    cpc: 16.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "seo-tools",
    affiliateScore: 90,
  },
  {
    keyword: "mangools discount",
    volume: 2400,
    kd: 22,
    cpc: 12.50,
    intent: "transactional" as BuyerIntent,
    modifiers: ["discount"] as IntentModifier[],
    niche: "seo-tools",
    affiliateScore: 94,
  },
  {
    keyword: "ubersuggest vs semrush",
    volume: 5600,
    kd: 35,
    cpc: 14.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "seo-tools",
    affiliateScore: 88,
  },
  {
    keyword: "semrush coupon code",
    volume: 6800,
    kd: 48,
    cpc: 24.50,
    intent: "transactional" as BuyerIntent,
    modifiers: ["coupon"] as IntentModifier[],
    niche: "seo-tools",
    affiliateScore: 98,
  },
  {
    keyword: "best keyword research tool",
    volume: 18200,
    kd: 55,
    cpc: 15.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "seo-tools",
    affiliateScore: 89,
  },

  // Email Marketing
  {
    keyword: "convertkit review 2024",
    volume: 2900,
    kd: 35,
    cpc: 8.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "email-marketing",
    affiliateScore: 88,
  },
  {
    keyword: "mailchimp alternatives",
    volume: 12100,
    kd: 48,
    cpc: 9.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["alternative"] as IntentModifier[],
    niche: "email-marketing",
    affiliateScore: 90,
  },
  {
    keyword: "best email marketing software",
    volume: 22000,
    kd: 58,
    cpc: 14.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "email-marketing",
    affiliateScore: 91,
  },
  {
    keyword: "convertkit vs mailerlite",
    volume: 4200,
    kd: 32,
    cpc: 7.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "email-marketing",
    affiliateScore: 86,
  },
  {
    keyword: "getresponse discount",
    volume: 1800,
    kd: 25,
    cpc: 10.20,
    intent: "transactional" as BuyerIntent,
    modifiers: ["discount"] as IntentModifier[],
    niche: "email-marketing",
    affiliateScore: 93,
  },
  {
    keyword: "aweber vs constant contact",
    volume: 3100,
    kd: 28,
    cpc: 8.90,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "email-marketing",
    affiliateScore: 84,
  },

  // VPN
  {
    keyword: "nordvpn coupon code",
    volume: 22000,
    kd: 68,
    cpc: 6.80,
    intent: "transactional" as BuyerIntent,
    modifiers: ["coupon"] as IntentModifier[],
    niche: "vpn",
    affiliateScore: 98,
  },
  {
    keyword: "cheapest vpn service",
    volume: 5400,
    kd: 38,
    cpc: 5.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["cheapest"] as IntentModifier[],
    niche: "vpn",
    affiliateScore: 82,
  },
  {
    keyword: "best vpn for streaming",
    volume: 33000,
    kd: 62,
    cpc: 8.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "vpn",
    affiliateScore: 88,
  },
  {
    keyword: "expressvpn vs nordvpn",
    volume: 18500,
    kd: 55,
    cpc: 7.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "vpn",
    affiliateScore: 92,
  },
  {
    keyword: "surfshark review 2024",
    volume: 8900,
    kd: 42,
    cpc: 6.10,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "vpn",
    affiliateScore: 86,
  },
  {
    keyword: "best vpn for privacy",
    volume: 12200,
    kd: 48,
    cpc: 7.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "vpn",
    affiliateScore: 85,
  },
  {
    keyword: "expressvpn discount deal",
    volume: 4500,
    kd: 35,
    cpc: 9.50,
    intent: "transactional" as BuyerIntent,
    modifiers: ["discount", "deal"] as IntentModifier[],
    niche: "vpn",
    affiliateScore: 96,
  },

  // Finance
  {
    keyword: "best credit cards for travel",
    volume: 33000,
    kd: 72,
    cpc: 22.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "finance",
    affiliateScore: 85,
  },
  {
    keyword: "best investment apps 2024",
    volume: 18500,
    kd: 58,
    cpc: 18.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "finance",
    affiliateScore: 82,
  },
  {
    keyword: "robinhood vs webull",
    volume: 27000,
    kd: 45,
    cpc: 12.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "finance",
    affiliateScore: 88,
  },
  {
    keyword: "best high yield savings account",
    volume: 40500,
    kd: 65,
    cpc: 16.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "finance",
    affiliateScore: 80,
  },
  {
    keyword: "sofi review",
    volume: 12100,
    kd: 42,
    cpc: 14.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "finance",
    affiliateScore: 84,
  },
  {
    keyword: "best budgeting apps",
    volume: 22000,
    kd: 52,
    cpc: 8.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "finance",
    affiliateScore: 78,
  },

  // Online Courses
  {
    keyword: "udemy vs coursera",
    volume: 9900,
    kd: 32,
    cpc: 4.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "online-courses",
    affiliateScore: 78,
  },
  {
    keyword: "best online courses for python",
    volume: 14800,
    kd: 45,
    cpc: 6.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "online-courses",
    affiliateScore: 82,
  },
  {
    keyword: "skillshare free trial",
    volume: 33000,
    kd: 38,
    cpc: 3.80,
    intent: "transactional" as BuyerIntent,
    modifiers: ["deal"] as IntentModifier[],
    niche: "online-courses",
    affiliateScore: 90,
  },
  {
    keyword: "masterclass review",
    volume: 18200,
    kd: 42,
    cpc: 5.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "online-courses",
    affiliateScore: 85,
  },
  {
    keyword: "linkedin learning vs udemy",
    volume: 5400,
    kd: 28,
    cpc: 4.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "online-courses",
    affiliateScore: 80,
  },

  // Software/SaaS
  {
    keyword: "notion vs clickup comparison",
    volume: 4400,
    kd: 28,
    cpc: 7.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs", "comparison"] as IntentModifier[],
    niche: "software",
    affiliateScore: 85,
  },
  {
    keyword: "is grammarly worth it",
    volume: 18000,
    kd: 42,
    cpc: 5.60,
    intent: "commercial" as BuyerIntent,
    modifiers: ["worth it"] as IntentModifier[],
    niche: "software",
    affiliateScore: 88,
  },
  {
    keyword: "best project management software",
    volume: 33000,
    kd: 62,
    cpc: 12.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "software",
    affiliateScore: 86,
  },
  {
    keyword: "canva pro review",
    volume: 14800,
    kd: 35,
    cpc: 4.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "software",
    affiliateScore: 84,
  },
  {
    keyword: "asana vs monday",
    volume: 9900,
    kd: 38,
    cpc: 14.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "software",
    affiliateScore: 90,
  },
  {
    keyword: "adobe creative cloud discount",
    volume: 8100,
    kd: 48,
    cpc: 8.50,
    intent: "transactional" as BuyerIntent,
    modifiers: ["discount"] as IntentModifier[],
    niche: "software",
    affiliateScore: 92,
  },
  {
    keyword: "best crm software for small business",
    volume: 12100,
    kd: 55,
    cpc: 18.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "software",
    affiliateScore: 87,
  },
  {
    keyword: "slack alternatives",
    volume: 22000,
    kd: 42,
    cpc: 6.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["alternative"] as IntentModifier[],
    niche: "software",
    affiliateScore: 83,
  },

  // Fitness
  {
    keyword: "best protein powder for muscle gain",
    volume: 27000,
    kd: 58,
    cpc: 3.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 75,
  },
  {
    keyword: "whoop vs apple watch",
    volume: 14800,
    kd: 35,
    cpc: 2.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 82,
  },
  {
    keyword: "best home gym equipment",
    volume: 33000,
    kd: 52,
    cpc: 4.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 78,
  },
  {
    keyword: "peloton review 2024",
    volume: 9900,
    kd: 42,
    cpc: 5.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["review"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 80,
  },
  {
    keyword: "best fitness tracker",
    volume: 40500,
    kd: 62,
    cpc: 3.50,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 76,
  },
  {
    keyword: "optimum nutrition vs dymatize",
    volume: 5600,
    kd: 28,
    cpc: 2.80,
    intent: "commercial" as BuyerIntent,
    modifiers: ["vs"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 74,
  },
  {
    keyword: "myfitnesspal premium worth it",
    volume: 6800,
    kd: 32,
    cpc: 3.20,
    intent: "commercial" as BuyerIntent,
    modifiers: ["worth it"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 79,
  },
  {
    keyword: "best pre workout supplement",
    volume: 22000,
    kd: 55,
    cpc: 2.90,
    intent: "commercial" as BuyerIntent,
    modifiers: ["best"] as IntentModifier[],
    niche: "fitness",
    affiliateScore: 72,
  },
]

// Affiliate score thresholds
export const AFFILIATE_SCORE_TIERS = {
  excellent: { min: 90, label: "Excellent", color: "text-emerald-400", bg: "bg-emerald-500/10" },
  good: { min: 75, label: "Good", color: "text-cyan-400", bg: "bg-cyan-500/10" },
  moderate: { min: 50, label: "Moderate", color: "text-amber-400", bg: "bg-amber-500/10" },
  low: { min: 0, label: "Low", color: "text-red-400", bg: "bg-red-500/10" },
}
